### ISSUE TITLE
Getting Neolink in Home Assistant working

### ISSUE THREAD

**Issue by Tobster77** [dm82m/hassio-addons#35]
**Describe the bug**
Instructions for Home Assistant are not fully clear

**To Reproduce**
1. Install Neolink as an Home Assistant Add-on
2. Add-on is running (according to log):
```--- VERSIONS ---
add-on version: 0.0.9
[2024-05-31T18:50:19Z INFO  neolink] Neolink e47a0d5734b0a06b53bd8d78be9ca2f6b8396480 release
neolink version: neolink 0.6.2
neolink mode: dual
neolink log: info
ATTENTION: if you expected a newer Neolink version, please reinstall this Add-on!
--- Neolink ---
[2024-05-31T18:50:19Z INFO  neolink] Neolink e47a0d5734b0a06b53bd8d78be9ca2f6b8396480 release
[2024-05-31T18:50:20Z WARN  neolink::rtsp] Without a server certificate, usernames and passwords will be exchanged in plaintext!
[2024-05-31T18:50:20Z INFO  neolink::rtsp] Kamera_Kellerausgang: Rtsp Staring
[2024-05-31T18:50:20Z INFO  neolink::rtsp] Starting RTSP Server at 0.0.0.0:8554
[2024-05-31T18:50:20Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: xxxxxxxxxxxx 
[2024-05-31T18:50:20Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-05-31T18:50:20Z INFO  neolink::mqtt] Kamera_Kellerausgang: MQTT Staring
[2024-05-31T18:50:20Z INFO  neolink::mqtt::discovery] Enabled MQTT discovery for Kamera_Kellerausgang with friendly name Kamera Kellerausgang
[2024-05-31T18:50:20Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-05-31T18:50:21Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-05-31T18:50:21Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-05-31T18:50:22Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxx at 192.168.178.65:38650
[2024-05-31T18:50:22Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-05-31T18:50:23Z INFO  neolink::utils] Kamera_Kellerausgang: Connected and logged in
[2024-05-31T18:50:24Z INFO  neolink::common::camthread] Kamera_Kellerausgang: Camera time is already set: 2024-05-31 20:50:24.0 -01:00:00
[2024-05-31T18:50:24Z INFO  neolink::common::neocam] Kamera_Kellerausgang: Model Argus 3 Ultra
[2024-05-31T18:50:24Z INFO  neolink::common::neocam] Kamera_Kellerausgang: Firmware Version v3.0.0.2355_23062001
[2024-05-31T18:50:25Z INFO  neolink::rtsp] Kamera_Kellerausgang: Avaliable at /Kamera_Kellerausgang/sub, /Kamera_Kellerausgang/Sub, /Kamera_Kellerausgang/subStream, /Kamera_Kellerausgang/SubStream, /Kamera_Kellerausgang/Substream, /Kamera_Kellerausgang/substream
[2024-05-31T18:50:25Z INFO  neolink::rtsp] Kamera_Kellerausgang: Avaliable at /Kamera_Kellerausgang/main, /Kamera_Kellerausgang/Main, /Kamera_Kellerausgang/mainStream, /Kamera_Kellerausgang/MainStream, /Kamera_Kellerausgang/Mainstream, /Kamera_Kellerausgang/mainstream, /Kamera_Kellerausgang
```
4. A Reolink device is auto-discovered in Home Assistant. But the connections fails
```Client connector error during login of host 192.168.178.65:443: Host 192.168.178.65:443: connection error: Cannot connect to host 192.168.178.65:443 ssl:default [Connect call failed ('192.168.178.65', 443)]```
To be honest, I am quite confused. 

- Is the Reolink integration the right one for the further steps, or do I need a different integration to have the cam running in Home Assistant?
- Should I connect to the camera itself (192.168.178.65) or the RTSP server provided (would that be localhost?)? 
- Which credentials are to be used? Those I defined in the neolink.toml for the RTSP proxy, or those for the cam ("admin" and password)?
- How can I employ the abilities provided via MQTT? I have fundamental knowledge and the Mosquitto server running in Home Assistant for Zigbee2MQTT, but general instructions would be fine.

**Expected behavior**
What next to get the device showing up in Home Assistant?

**Versions**
NVR software: None, I would like to use the cam in Home Assistant
Neolink software: none
Reolink camera model and firmware: Reolink Argus 3 Ultra

I posted this originally [here](https://github.com/QuantumEntangledAndy/neolink/issues/262), but @QuantumEntangledAndy advised me to place my request at the add-on repository.

Thank you!

**Comment by dm82m** [comment]
From within home assistant try to access the rtsp cameras stream with `localhost:8443/Kamera_Kellerausgang/main`

to add rtsp camera generally to home assistant you can use that one: https://www.home-assistant.io/integrations/rtsp_to_webrtc/

**Comment by Tobster77** [comment]
This is a Reolink Argus 3 Ultra.

Just to be sure: It is port 8443? The example.toml chooses port 8554. Still, both ports do not work. This is my setting for a "Generic Cam" in Home Assistant which should be able to receive the image, as far as I understood:

![image](https://github.com/dm82m/hassio-addons/assets/46224926/21f81a8b-ee79-4047-9dbd-3eb6c005765c)

So should this work?

**Comment by dm82m** [comment]
Port 8554, sorry my mistake.

try accessing the rtsp stream with vlc: https://www.ueberwachungskamera-berater.de/artikel/rtsp-stream-oeffnen-mit-vlc

instead of localhost use the ip of your home assistant server.

**Comment by Tobster77** [comment]
Thanks a lot...
VLC works nicely with the RTSP stream.

**Comment by dm82m** [comment]
Then my addon and neolink of Andy is successful running.

what you need to do is to integrate the RTSP stream to home assistant. I would do that with Webrtc camera cause it is lag free. Check this: https://github.com/AlexxIT/WebRTC

Install it with hacw and simply add the RTSP stream to your Lovelace dashboard.

**Comment by dm82m** [comment]
@Tobster77 how is it going?

**Comment by Tobster77** [comment]
@dm82m, thanks for asking. I was basically successful in getting it running after some discussions qith @QuantumEntangledAndy. However, it is very unreliable and the Neolink RTSP server crashes after some minutes to hours:
```
...
...
        Dropped connection
[2024-06-03T06:59:24Z INFO  neolink::common::camthread] Attempt reconnect in 50ms
[2024-06-03T06:59:24Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: xxxxxxxxxxxxx
[2024-06-03T06:59:24Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-06-03T06:59:24Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-06-03T06:59:25Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-06-03T06:59:25Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-06-03T06:59:26Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxxx at 192.168.178.65:56125
[2024-06-03T06:59:26Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-03T06:59:31Z INFO  neolink::utils] Kamera_Kellerausgang: Connected and logged in
...
...
[2024-06-03T10:00:53Z INFO  neolink::utils] Kamera_Kellerausgang: Connected and logged in
[2024-06-03T10:00:53Z INFO  neolink::common::camthread] Kamera_Kellerausgang: Camera time is already set: 2024-06-03 12:00:52.0 -01:00:00
thread '<unnamed>' panicked at 'Could not build pipeline: channel closed', src/rtsp/gst/factory.rs:132:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
/run.sh: line 35:    13 Aborted                 (core dumped) neolink mqtt-rtsp --config /config/addons/neolink.toml
--- VERSIONS ---
add-on version: 0.0.9
neolink version: neolink 0.6.2
[2024-06-03T11:27:33Z INFO  neolink] Neolink e47a0d5734b0a06b53bd8d78be9ca2f6b8396480 release
neolink mode: dual
neolink log: info
ATTENTION: if you expected a newer Neolink version, please reinstall this Add-on!
--- Neolink ---
[2024-06-03T11:27:33Z INFO  neolink] Neolink e47a0d5734b0a06b53bd8d78be9ca2f6b8396480 release
[2024-06-03T11:27:34Z WARN  neolink::rtsp] Without a server certificate, usernames and passwords will be exchanged in plaintext!
[2024-06-03T11:27:34Z INFO  neolink::rtsp] Kamera_Kellerausgang: Rtsp Staring
[2024-06-03T11:27:34Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: xxxxxxxxxxxxx
[2024-06-03T11:27:34Z INFO  neolink::rtsp] Starting RTSP Server at 0.0.0.0:8554
[2024-06-03T11:27:34Z INFO  neolink::mqtt] Kamera_Kellerausgang: MQTT Staring
[2024-06-03T11:27:34Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-06-03T11:27:35Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-06-03T11:27:36Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-06-03T11:27:36Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-06-03T11:27:48Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxxx at 192.168.178.65:56125
[2024-06-03T11:27:48Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-03T11:27:58Z WARN  neolink::common::camthread] Connection Lost: IO Error: Custom { kind: Other, error: DroppedConnection }
    
    Caused by:
        Dropped connection
[2024-06-03T11:27:58Z INFO  neolink::common::camthread] Attempt reconnect in 50ms
[2024-06-03T11:27:58Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: xxxxxxxxxxxxx
[2024-06-03T11:27:58Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-06-03T11:28:00Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-06-03T11:28:00Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-06-03T11:28:00Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-06-03T11:28:13Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxxx at 192.168.178.65:56125
[2024-06-03T11:28:13Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-03T11:28:23Z WARN  neolink::common::camthread] Connection Lost: IO Error: Custom { kind: Other, error: DroppedConnection }
    
    Caused by:
        Dropped connection
[2024-06-03T11:28:23Z INFO  neolink::common::camthread] Attempt reconnect in 100ms
[2024-06-03T11:28:23Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: xxxxxxxxxxxxx
[2024-06-03T11:28:23Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-06-03T11:28:24Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-06-03T11:28:25Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-06-03T11:28:25Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-06-03T11:28:37Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxxx at 192.168.178.65:56125
[2024-06-03T11:28:37Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-03T11:28:47Z WARN  neolink::common::camthread] Connection Lost: IO Error: Custom { kind: Other, error: DroppedConnection }
    
    Caused by:
        Dropped connection
[2024-06-03T11:28:47Z INFO  neolink::common::camthread] Attempt reconnect in 200ms
[2024-06-03T11:28:47Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: xxxxxxxxxxxxx
[2024-06-03T11:28:47Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-06-03T11:28:50Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-06-03T11:28:51Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-06-03T11:28:51Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-06-03T11:29:03Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxxx at 192.168.178.65:56125
[2024-06-03T11:29:03Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-03T11:29:13Z WARN  neolink::common::camthread] Connection Lost: IO Error: Custom { kind: Other, error: DroppedConnection }
    
    Caused by:
        Dropped connection
[2024-06-03T11:29:13Z INFO  neolink::common::camthread] Attempt reconnect in 400ms
[2024-06-03T11:29:13Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: xxxxxxxxxxxxx 
[2024-06-03T11:29:13Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-06-03T11:29:15Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-06-03T11:29:15Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-06-03T11:29:15Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-06-03T11:29:28Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxxx at 192.168.178.65:56125
[2024-06-03T11:29:28Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-03T11:29:38Z WARN  neolink::common::camthread] Connection Lost: IO Error: Custom { kind: Other, error: DroppedConnection }
    
    Caused by:
        Dropped connection
[2024-06-03T11:29:38Z INFO  neolink::common::camthread] Attempt reconnect in 800ms
[2024-06-03T11:29:38Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: 95270006TIZ21QI9
[2024-06-03T11:29:38Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-06-03T11:29:40Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-06-03T11:29:41Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-06-03T11:29:41Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-06-03T11:29:42Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxxx at 192.168.178.65:56125
[2024-06-03T11:29:42Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-03T11:29:51Z INFO  neolink::utils] Kamera_Kellerausgang: Connected and logged in
[2024-06-03T11:29:52Z INFO  neolink::common::camthread] Kamera_Kellerausgang: Camera time is already set: 2024-06-03 13:29:51.0 -01:00:00
[2024-06-03T11:29:53Z INFO  neolink::common::neocam] Kamera_Kellerausgang: Model Argus 3 Ultra
[2024-06-03T11:29:53Z INFO  neolink::common::neocam] Kamera_Kellerausgang: Firmware Version v3.0.0.2355_23062001
[2024-06-03T11:29:55Z INFO  neolink::rtsp] Kamera_Kellerausgang: Avaliable at /Kamera_Kellerausgang/main, /Kamera_Kellerausgang/Main, /Kamera_Kellerausgang/mainStream, /Kamera_Kellerausgang/MainStream, /Kamera_Kellerausgang/Mainstream, /Kamera_Kellerausgang/mainstream, /Kamera_Kellerausgang
[2024-06-03T11:29:55Z INFO  neolink::rtsp] Kamera_Kellerausgang: Activating Client
[2024-06-03T11:29:55Z INFO  neolink::rtsp] Kamera_Kellerausgang: Pausing Client
[2024-06-03T11:29:56Z INFO  neolink::rtsp] Kamera_Kellerausgang: Activating Client
[2024-06-03T11:29:56Z INFO  neolink::rtsp] Kamera_Kellerausgang: Pausing Client
[2024-06-03T11:29:56Z INFO  neolink::rtsp] Kamera_Kellerausgang: Avaliable at /Kamera_Kellerausgang/sub, /Kamera_Kellerausgang/Sub, /Kamera_Kellerausgang/subStream, /Kamera_Kellerausgang/SubStream, /Kamera_Kellerausgang/Substream, /Kamera_Kellerausgang/substream
[2024-06-03T11:29:59Z WARN  neolink_core::bc_protocol::snap] Snap did not recieve expected number of byes
[2024-06-03T11:30:35Z WARN  neolink_core::bc_protocol::snap] Snap did not recieve expected number of byes
[2024-06-03T11:30:47Z WARN  neolink_core::bc_protocol::snap] Snap did not recieve expected number of byes
[2024-06-03T11:31:10Z WARN  neolink_core::bc_protocol::snap] Snap did not recieve expected number of byes
[2024-06-03T11:31:24Z WARN  neolink_core::bc_protocol::snap] Snap did not recieve expected number of byes
...```

**Comment by Tobster77** [comment]
Another crash scenario:
```--- VERSIONS ---
add-on version: 0.0.9
neolink version: neolink 0.6.2
[2024-06-03T11:35:51Z INFO  neolink] Neolink e47a0d5734b0a06b53bd8d78be9ca2f6b8396480 release
neolink mode: dual
neolink log: info
ATTENTION: if you expected a newer Neolink version, please reinstall this Add-on!
--- Neolink ---
[2024-06-03T11:35:51Z INFO  neolink] Neolink e47a0d5734b0a06b53bd8d78be9ca2f6b8396480 release
[2024-06-03T11:35:52Z WARN  neolink::rtsp] Without a server certificate, usernames and passwords will be exchanged in plaintext!
[2024-06-03T11:35:52Z INFO  neolink::rtsp] Kamera_Kellerausgang: Rtsp Staring
[2024-06-03T11:35:52Z INFO  neolink::rtsp] Starting RTSP Server at 0.0.0.0:8554
[2024-06-03T11:35:52Z INFO  neolink::mqtt] Kamera_Kellerausgang: MQTT Staring
[2024-06-03T11:35:52Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: xxxxxxxxxxxx
[2024-06-03T11:35:52Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-06-03T11:35:54Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-06-03T11:35:54Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-06-03T11:35:54Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-06-03T11:35:56Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxx at 192.168.178.65:24468
[2024-06-03T11:35:56Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-03T11:36:04Z INFO  neolink::utils] Kamera_Kellerausgang: Connected and logged in
[2024-06-03T11:36:05Z INFO  neolink::common::camthread] Kamera_Kellerausgang: Camera time is already set: 2024-06-03 13:36:04.0 -01:00:00
[2024-06-03T11:36:05Z INFO  neolink::common::neocam] Kamera_Kellerausgang: Model Argus 3 Ultra
[2024-06-03T11:36:05Z INFO  neolink::common::neocam] Kamera_Kellerausgang: Firmware Version v3.0.0.2355_23062001
[2024-06-03T11:36:06Z INFO  neolink::rtsp] Kamera_Kellerausgang: Avaliable at /Kamera_Kellerausgang/sub, /Kamera_Kellerausgang/Sub, /Kamera_Kellerausgang/subStream, /Kamera_Kellerausgang/SubStream, /Kamera_Kellerausgang/Substream, /Kamera_Kellerausgang/substream
[2024-06-03T11:36:06Z INFO  neolink::rtsp] Kamera_Kellerausgang: Activating Client
[2024-06-03T11:36:06Z INFO  neolink::rtsp] Kamera_Kellerausgang: Pausing Client
[2024-06-03T11:36:06Z INFO  neolink::rtsp] Kamera_Kellerausgang: Avaliable at /Kamera_Kellerausgang/main, /Kamera_Kellerausgang/Main, /Kamera_Kellerausgang/mainStream, /Kamera_Kellerausgang/MainStream, /Kamera_Kellerausgang/Mainstream, /Kamera_Kellerausgang/mainstream, /Kamera_Kellerausgang
[2024-06-03T11:36:06Z INFO  neolink::rtsp] Kamera_Kellerausgang: Activating Client
[2024-06-03T11:36:06Z INFO  neolink::rtsp] Kamera_Kellerausgang: Pausing Client
[2024-06-03T11:36:52Z INFO  neolink::rtsp] Kamera_Kellerausgang: Activating Client
[2024-06-03T11:41:03Z INFO  neolink::rtsp] Kamera_Kellerausgang: Pausing Client
[2024-06-03T11:58:18Z INFO  neolink::rtsp] Kamera_Kellerausgang: Activating Client
[2024-06-03T12:03:24Z INFO  neolink::rtsp] Kamera_Kellerausgang: Pausing Client
[2024-06-03T12:04:16Z INFO  neolink::rtsp] Kamera_Kellerausgang: Activating Client
[2024-06-03T12:06:05Z WARN  neolink::common::camthread] Connection Lost: IO Error: Custom { kind: Other, error: DroppedConnection }
    
    Caused by:
        Dropped connection
[2024-06-03T12:06:05Z INFO  neolink::common::camthread] Attempt reconnect in 50ms
[2024-06-03T12:06:05Z INFO  neolink::utils] Kamera_Kellerausgang: Connecting to camera at UID: xxxxxxxxxxxx
[2024-06-03T12:06:05Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying local discovery
[2024-06-03T12:06:06Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying remote discovery
[2024-06-03T12:06:06Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying map discovery
[2024-06-03T12:06:06Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Trying relay discovery
[2024-06-03T12:06:08Z INFO  neolink_core::bc_protocol] Kamera_Kellerausgang: Remote discovery success xxxxxxxxxxxx at 192.168.178.65:24468
[2024-06-03T12:06:08Z INFO  neolink::utils] Kamera_Kellerausgang: Logging in
[2024-06-03T12:06:09Z INFO  neolink::utils] Kamera_Kellerausgang: Connected and logged in
[2024-06-03T12:06:10Z INFO  neolink::common::camthread] Kamera_Kellerausgang: Camera time is already set: 2024-06-03 14:06:08.0 -01:00:00
thread '<unnamed>' panicked at 'Could not build pipeline: channel closed', src/rtsp/gst/factory.rs:132:56
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
/run.sh: line 35:    13 Aborted                 (core dumped) neolink mqtt-rtsp --config /config/addons/neolink.toml```

**Comment by Tobster77** [comment]
Is there anything I can provide? Thanks.

**Comment by dm82m** [comment]
No. That is all related to neolink and not my addon. So you should continue discussion with Andy.
